# Generated by Django 5.0 on 2023-12-13 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(help_text='Идентификатор организации в БД', primary_key=True, serialize=False)),
                ('full_name', models.TextField(help_text='Полное наименование организации', verbose_name='Полное наименование')),
                ('short_name', models.TextField(blank=True, help_text='Сокращенное наименование организации', null=True, verbose_name='Сокращенное наименование')),
                ('inn', models.CharField(blank=True, help_text='ИНН организации', max_length=12, null=True, verbose_name='ИНН')),
                ('factual_address', models.TextField(help_text='Адрес местонахождения организации', verbose_name='Адрес')),
                ('date_added', models.DateTimeField(auto_now=True, help_text='Дата внесения организации в БД', verbose_name='Дата создания организации в БД')),
                ('longitude', models.FloatField(help_text='Долгота расположения организации', verbose_name='Долгота')),
                ('latitude', models.FloatField(help_text='Широта расположения организации', verbose_name='Широта')),
                ('site', models.CharField(blank=True, help_text='Сайт организации', max_length=100, null=True, verbose_name='Сайт организации')),
                ('email', models.EmailField(blank=True, help_text='E-mail организации', max_length=100, null=True, verbose_name='E-mail организации')),
                ('is_gov', models.BooleanField(default=False, help_text='Является ли организация государственной', verbose_name='Государственная?')),
                ('is_full_time', models.BooleanField(default=False, help_text='Является ли организация круглосуточной', verbose_name='Круглосуточная?')),
                ('about', models.TextField(blank=True, help_text='Дополнительная информация об организации', null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст отзыва')),
                ('estimation', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации отзыва')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
